"""Add a column description

Revision ID: 7fdf5388d00b
Revises: 37c274307da2
Create Date: 2024-09-23 04:21:20.452448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdf5388d00b'
down_revision: Union[str, None] = '37c274307da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_categories_description'), 'categories', ['description'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_description'), table_name='categories')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
