version: "3.4"

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${MYSQL_PORT}

  python:
    build: ../python
    depends_on:
      - mysql
    restart: always
    volumes:
      - "../python:/python"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}

      - EMAIL_ADMIN_DEFAULT=${EMAIL_ADMIN_DEFAULT}
      - PASSWORD_ADMIN_DEFAULT=${PASSWORD_ADMIN_DEFAULT}

      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}

      - MYSQL_DATABASE=${MYSQL_DATABASE}

      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      
      - JWT_SECURITY_ALGORITHM=${JWT_SECURITY_ALGORITHM}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRE_SECONDS=${JWT_EXPIRE_SECONDS}
