version: "3"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    volumes:
      - "./data:/var/lib/mysql"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    logging:
      driver: none
  backend:
    build:
      context: "./backend"
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    environment:
      - SERVER_PORT=${SERVER_PORT}

      - EMAIL_ADMIN_DEFAULT=${EMAIL_ADMIN_DEFAULT}
      - PASSWORD_ADMIN_DEFAULT=${PASSWORD_ADMIN_DEFAULT}

      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}

      - MYSQL_DATABASE=${MYSQL_DATABASE}

      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

      - JWT_SECURITY_ALGORITHM=${JWT_SECURITY_ALGORITHM}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRE_SECONDS=${JWT_EXPIRE_SECONDS}

      - OTP_EXPIRE_SECONDS=${OTP_EXPIRE_SECONDS}

  frontend:
    build:
      context: "./frontend"
    depends_on: 
      - backend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
    environment:
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true


       