"""add otp user table

Revision ID: 426cd07a8da5
Revises: d80b10a49900
Create Date: 2024-09-27 03:13:33.244854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426cd07a8da5'
down_revision: Union[str, None] = 'd80b10a49900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_enable_otp', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp_secret', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('otp_qr_code', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('otp_recovery', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_recovery')
    op.drop_column('users', 'otp_qr_code')
    op.drop_column('users', 'otp_secret')
    op.drop_column('users', 'is_enable_otp')
    # ### end Alembic commands ###
