# """create 3 table

# Revision ID: 5f207d1157c7
# Revises: 54d3d8860c20
# Create Date: 2024-09-24 04:35:45.635675

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '5f207d1157c7'
# down_revision: Union[str, None] = '54d3d8860c20'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('categories',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(length=255), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
#     op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
#     op.create_table('posts',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('title', sa.String(length=255), nullable=True),
#     sa.Column('content', sa.Text(), nullable=True),
#     sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('user_id', sa.Integer(), nullable=True),
#     sa.Column('category_id', sa.Integer(), nullable=True),
#     sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
#     op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
#     op.create_table('comments',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('text', sa.Text(), nullable=True),
#     sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('user_id', sa.Integer(), nullable=True),
#     sa.Column('post_id', sa.Integer(), nullable=True),
#     sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_comments_id'), table_name='comments')
#     op.drop_table('comments')
#     op.drop_index(op.f('ix_posts_title'), table_name='posts')
#     op.drop_index(op.f('ix_posts_id'), table_name='posts')
#     op.drop_table('posts')
#     op.drop_index(op.f('ix_categories_name'), table_name='categories')
#     op.drop_index(op.f('ix_categories_id'), table_name='categories')
#     op.drop_table('categories')
#     # ### end Alembic commands ###
