# """add otp_qr_code

# Revision ID: a2d78f990b7a
# Revises: ecdaa95d7e9a
# Create Date: 2024-09-25 01:49:50.323811

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'a2d78f990b7a'
# down_revision: Union[str, None] = 'ecdaa95d7e9a'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('otp_qr_code', sa.Text(), nullable=True))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('users', 'otp_qr_code')
#     # ### end Alembic commands ###
