"""add is_enable_otp

Revision ID: c20470d72ee9
Revises: ccc4c7243cf7
Create Date: 2024-09-25 03:20:50.411414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20470d72ee9'
down_revision: Union[str, None] = 'ccc4c7243cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_enable_otp', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_enable_otp')
    # ### end Alembic commands ###
