"""LargeBinary otp_secret

Revision ID: ccc4c7243cf7
Revises: cf09c0a711bf
Create Date: 2024-09-25 02:55:58.197794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccc4c7243cf7'
down_revision: Union[str, None] = 'cf09c0a711bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_secret',
               existing_type=mysql.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'otp_secret',
               existing_type=sa.LargeBinary(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
