# """text otp_secret

# Revision ID: cf09c0a711bf
# Revises: a2d78f990b7a
# Create Date: 2024-09-25 02:35:12.655077

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import mysql

# # revision identifiers, used by Alembic.
# revision: str = 'cf09c0a711bf'
# down_revision: Union[str, None] = 'a2d78f990b7a'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'otp_secret',
#                existing_type=mysql.VARCHAR(length=255),
#                type_=sa.Text(),
#                existing_nullable=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('users', 'otp_secret',
#                existing_type=sa.Text(),
#                type_=mysql.VARCHAR(length=255),
#                existing_nullable=True)
#     # ### end Alembic commands ###
