# """add otp_recovery

# Revision ID: d56f66bb65ff
# Revises: c20470d72ee9
# Create Date: 2024-09-26 03:11:13.775046

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'd56f66bb65ff'
# down_revision: Union[str, None] = 'c20470d72ee9'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('otp_recovery', sa.JSON(), nullable=True))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('users', 'otp_recovery')
#     # ### end Alembic commands ###
