# """add description

# Revision ID: ecdaa95d7e9a
# Revises: 5f207d1157c7
# Create Date: 2024-09-24 04:36:41.559946

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'ecdaa95d7e9a'
# down_revision: Union[str, None] = '5f207d1157c7'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('categories', sa.Column('description', sa.String(length=255), nullable=True))
#     op.create_index(op.f('ix_categories_description'), 'categories', ['description'], unique=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_categories_description'), table_name='categories')
#     op.drop_column('categories', 'description')
#     # ### end Alembic commands ###
